### ISSUE TITLE
Ubuntu 18.04 prerequisites

### ISSUE THREAD

**Issue by mtbc** [openmicroscopy/ome-documentation#1995]
Working through https://docs.openmicroscopy.org/omero/5.5.0/sysadmins/unix/server-ubuntu1804-ice36.html#installing-prerequisites I found that for the Ice installation,

> As part of the installation of Ice, two new daemons are installed and automatically started.

was not true. Further, `mv opt/Ice-3.6.4 /opt` did not leave the Ice binaries on the default PATH.

**Comment by jburel** [comment]
https://github.com/ome/ome-documentation/pull/1998
