### ISSUE TITLE
Ubuntu 18.04 documentation, ice/bin/ to PATH

### ISSUE THREAD

**Issue by inDane** [openmicroscopy/ome-documentation#1997]
I wanted to fork/edit the documentation, because this is not needed

`systemctl --now disable glacier2router icegridregistry`

but ice needs to be added to the PATH:

`echo "export PATH=\$PATH:/opt/Ice-3.6.4/bin" >> /etc/profile.d/ice-to-path.sh`

but then I found something on the editing page, that is not shown on the regular page.

```
To make Ice available to all users, set the environment using :download:`omero-ice36.env <walkthrough/omero-ice36.env>`::

    cat omero-ice36.env >> /etc/profile
```

Now I'm not sure how/if forking is fixing this. Can you please take a look?

Best regards

**Comment by jburel** [comment]
Thanks for the feedback
This has been fixed see https://github.com/ome/ome-documentation/pull/1994
The new doc has not been yet deployed.

**Comment by jburel** [comment]
The problem ``systemctl --now disable glacier2router icegridregistry`` has been mentioned in https://github.com/ome/ome-documentation/issues/1995

**Comment by jburel** [comment]
PR https://github.com/ome/ome-documentation/pull/1998
