### ISSUE TITLE
Ubuntu 18.04 RFE

### ISSUE THREAD

**Issue by dominikl** [openmicroscopy/ome-documentation#2070]
Some RFEs for the 18.04 ubuntu installation docs (still apply for the upcoming 5.6 docs):
- 'To make Ice available to all users, set the environment using omero-ice36.env':
Instead of linking to this 'omero-ice36.env' file, could we not have a command block like:
  ```
  echo "export ICE_HOME=/opt/ice-3.6.5-0.3.0" >> /etc/profile
  ...
  ```
  You can nicely follow through the doc with copy and pasting. Until there. Then you suddenly have to download a file, with wget or whatever. It's a bit odd. We list the full settings.env as well for example. No need to download that.
- The omero-server system user:
All the command blocks still have the 'omero' user, not the 'omero-server' user. I'm pretty sure I reviewed a PR which should have changed that actually. Not sure what happenend there.
- 'The following steps are run as the omero-server system user.'
Switching to the omero-server user is actually not that easy. As it's not a 'normal' user with login shell and password, you have to `sudo su` first (if not root already), then `su omero-server`, then run the bash with `bash --init-file /etc/profile` otherwise you don't have the correct PATH settings (I don't know why profile isn't loaded automatically to be honest). Any ideas how that can be made easier?
- The 'settings.env': Is this file still needed later? If not it should be deleted. It's not a good idea to have a plain text file with omero root and db passwords sitting around.

**Comment by manics** [comment]
sudo has several options for controlling the environment, something like `sudo -iu omero-server` may work

**Comment by jburel** [comment]
cf. point 2, It is b/c autogen has not been run since the PR was reviewed so the files have not been updated. If you download the doc from https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-docs-superbuild-build/52/, the commands should be for the ``omero-server`` user

**Comment by jburel** [comment]
The problem with point 1 is to extract each line, line by line from ``omero-ice36.env`` file and copy them to ``/etc/profile``and have all the lines in the same code block. 
Alternative is to print the content of ``omero-ice36.env`` and indicate to copy it to /etc/profile

**Comment by joshmoore** [comment]
> The problem with point 1 is to extract each line, line by line from omero-ice36.env file and copy them to /etc/profileand have all the lines in the same code block.

would an EOF help? e.g.

```
$ cat <<EOF > my-file
> foo
> bar
> EOF
/tmp $ cat my-file
foo
bar
```

**Comment by dominikl** [comment]
Thanks @jburel , the doc from merge-ci looks better.
@manics `sudo -iu omero-server` doesn't invoke /etc/profile either unfortunately. But what seems to work is changing the shell of the omero-server to bash `chsh -s /bin/bash omero-server`, then `su - omero-server` will include the /etc/profile. Don't know if we should make that part of the docs. Would make switching users during installation easier.

**Comment by joshmoore** [comment]
If so, then could the virtualenv also be activated as part of the profile to simplify things?

**Comment by jburel** [comment]
Unfortunately the ``EOF`` will not simplify things. Sphinx issue more than anything

**Comment by dominikl** [comment]
Once again I ran throught the docs ( https://docs.openmicroscopy.org/omero/5.6.0-m5/sysadmins/unix/server-ubuntu1804-ice36.html ), still a few things which could be improved:

`settings.env`: Where should this file be created? Later it is assumed, that it is in `/home/omero-server/` but this user doesn't exist yet. Suggestion: Create it in `/tmp/settings.env` and copy it later. And emphasise that you need to `source /tmp/settings.env` and also source it again everytime you switch users. This is assumed, but never explicitely mentioned.

Create a local omero-server system user, and ... : There's still a typo" `e.g. passwd omero` should be `e.g. passwd omero-server`.  Also this user actually needs a bash login shell. So why use `useradd` and not `adduser` (later should set these things up automatically)?.  More to that later. After the user creation the `/tmp/settings.env` needs to be copied into `/home/omero-server/`

The whole `/etc/profile` thing doesn't work. Ubuntu seems to completely ignore it. I got it nicely working now by giving omero-server user the bash shell (`usermod -s /bin/bash omero-server`) and adding the stuff to `/home/omero-server/.bash.rc`:
```
export ICE_HOME=/opt/ice-3.6.5-0.3.0
export PATH="$ICE_HOME/bin:$PATH"
#Remove commented out export below if Ice is not set globally accessible
#export LD_LIBRARY_PATH="$ICE_HOME/lib64:$ICE_HOME/lib:$LD_LIBRARY_PATH"
export SLICEPATH="$ICE_HOME/slice"
source ~/settings.env
```
(Note: Here again you need to source the settings.env otherwise `omero` command won't work).

The init.d script: Why not name the file appropriatly `omero-server` (not `omero-init.d`) and add instructions to copy that file to `/etc/init.d/`, make it executable and enable it with `systemctl enable omero-server`?

**Comment by jburel** [comment]
Few points will need to be adjusted in omero-install, few in the doc
Feel free to open PRs

**Comment by jburel** [comment]
@dominikl we use ``useradd`` mainly for portability since it is native and compiled with the system
The same "step" file is used for all the guides
``adduser`` is certainly more friendly

**Comment by jburel** [comment]
Closing. points have been addressed

**Comment by dominikl** [comment]
Thanks @jburel 👍
