### ISSUE TITLE
Decouple doc components

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/ome-documentation#2087]
Contrib and the omero docs should be moved to separate repositories. This repository should likely become a README explaining the locations of doc resources.

**Comment by jburel** [comment]
We now have 
*  https://ome-contributing.readthedocs.io/en/latest/ ->https://github.com/ome/ome-contributing
*  https://omero-insight.readthedocs.io/en/latest/ -> https://github.com/ome/omero-insight

**Comment by sbesson** [comment]
Should this be closed?

**Comment by jburel** [comment]
I think so. I forgot about that.
The question is: do we want to do more? Web is the most problematic (since we have "web" doc in many part) when I was looking at extracting it
