### ISSUE TITLE
OMERO.web systemd file is missing PATH

### ISSUE THREAD

**Issue by manics** [openmicroscopy/ome-documentation#2098]
Reported at https://forum.image.sc/t/release-of-omero-5-6-0-with-python-3/32983/2

https://docs.openmicroscopy.org/omero/5.6.0/sysadmins/unix/install-web/walkthrough/omeroweb-install-centos7-ice3.6.html#automatically-running-omero-web

The OMERO.web service file is missing a `PATH` environment variable that includes the virtual environment, which means gunicorn isn't found.

We should also investigate why this wasn't picked up by the CI tests.

**Comment by jburel** [comment]
See https://github.com/ome/omeroweb-install/pull/57

Only doc section for the gunicorn config, so nothing to be run by travis
