### ISSUE TITLE
OMERO.server upgrade page should mention omero-py

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/ome-documentation#2106]
E.g. https://docs.openmicroscopy.org/omero/5.6.0/sysadmins/server-upgrade.html
doesn't ask you to upgrade ```omero-py``` since this was not needed before decoupling (or even with the release of OMERO 5.6).

**Comment by joshmoore** [comment]
:+1: and optimally ETA of early next week.

**Comment by jburel** [comment]
See https://github.com/ome/ome-documentation/pull/2108
