### ISSUE TITLE
remove support for 3.5

### ISSUE THREAD

**Issue by jburel** [openmicroscopy/ome-documentation#2157]
Currently debian9 is the only platform coming with Python 3.5 by default
Work will be required in omero-install, omeroweb-install (see https://github.com/ome/omeroweb-install/pull/70) and doc repo

cc @manics

**Comment by sbesson** [comment]
Does this issue encompasses the work at the level of `omero-py`, `omero-web` and individual Python projects to mark them as Python 3.6+ compatible only?

**Comment by jburel** [comment]
it does, I should have listed them here too.
