### ISSUE TITLE
Clean up session directory

### ISSUE THREAD

**Issue by Hamedhm** [openmicroscopy/ome-documentation#2218]
We have an instance of Omero in production and it is recently causing the VM to perform poorly. We checked the session directory (omero/sessions) and there are 144K+ sessions there. I know that we may break some clients' connections by cleaning up this directory and just would like to make sure that we do not break the Omero on our side. Do you suggest this?

**Comment by joshmoore** [comment]
Hi @Hamedhm. Do you have any automated processes that are running on the server itself?

You are right that a `clean` or `garbage collect` step would be useful, but at the same time, I've not seen this problem before. Typically on the _client_ side, when a user logins in, an older, inactive session is cleaned up.

If the sessions are coming from an automated process and therefore aren't being re-used, then getting rid of the files will likely go unnoticed.

~Josh

P.S. depending on how such processes are being launched, you can have them use their own temporary sessions directory to make clean up easier.

**Comment by Hamedhm** [comment]
Hi @joshmoore 

Thank you for following this up. 

Yes, we have an automated process to upload 100K+ images to Omero, one by one by creating independent sessions; and we are the only clients that connect to that server (it is a dev server). 

I am planning to clean the sessions up and create a job that cleans them regularly.


Thank you so so much for your help.

**Comment by joshmoore** [comment]
@Hamedhm :+1: Glad to hear it.

See https://docs.openmicroscopy.org/omero/5.6.3/users/cli/sessions.html#sessions-directory if you want to attempt the separate sessions directory.

All the best.
