### ISSUE TITLE
Typo in the "OMERO.web installation on Ubuntu 18.04"

### ISSUE THREAD

**Issue by CamachoDejay** [openmicroscopy/ome-documentation#2239]
Hej,

I found a small typo in the [OMERO.web installation on Ubuntu 18.04](https://docs.openmicroscopy.org/omero/5.6.4/sysadmins/unix/install-web/walkthrough/omeroweb-install-ubuntu1804-ice3.6.html). In the section "Upgrade pip and install OMERO.web:" I believe the correct line would be:
"/opt/omero/web/venv3/bin/pip install --upgrade"... currently it says "–upgrade" which creates errors down the line.

Best,
Rafa

**Comment by jburel** [comment]
Thanks 
It looks like the formatting of the code snippet did not happen during the automatic page generation from https://github.com/ome/omeroweb-install/blob/master/ansible/templates/common/install.sh.j2

**Comment by CamachoDejay** [comment]
No worries, happy to help.

**Comment by jburel** [comment]
fixed in https://github.com/ome/omeroweb-install/pull/83
