### ISSUE TITLE
copright

### ISSUE THREAD

**Issue by haesleinhuepf** [openmicroscopy/ome-documentation#2368]
Hi @jburel et al,

I was just going through some training materials elaborating on licenses / copyright. This repository does not contain a `LICENSE` file and thus, it's hard to reuse the materials according to the FAIR principles. Would it be possible to add such a file here?

Thanks!

Best,
Robert

**Comment by jburel** [comment]
Thanks for spotting that. This is an oversight
I have now added a license file. Same license as Bio-Formats documentation i.e BSD 2-Clause Simplified License

**Comment by haesleinhuepf** [comment]
awesome thanks for the quick response!
