### ISSUE TITLE
Error in installing "OMERO.server installation on Ubuntu 18.04"

### ISSUE THREAD

**Issue by scuniff** [openmicroscopy/ome-documentation#2370]
I was doing the install via this link, https://docs.openmicroscopy.org/omero/5.6.0/sysadmins/unix/server-ubuntu1804-ice36.html

All was going well until I got this error:

**:      2023-11-05: Ubuntu bionic (18.04) and kinetic (22.10) removed from apt.postgresql.org.**

I was doing the command "**apt-get update**" from the Postgres section:

```
To install PostgreSQL 11:

apt-get install -y gnupg
echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
apt-get update
apt-get -y install postgresql-11
service postgresql start
```

Here is the logging:

root@ip-172-30-4-98:/tmp# wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
OK
root@ip-172-30-4-98:/tmp# **apt-get update**
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:4 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease
Err:5 http://apt.postgresql.org/pub/repos/apt bionic-pgdg Release
  **404  Not Found [IP: 147.75.85.69 80]**
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
**E: The repository 'http://apt.postgresql.org/pub/repos/apt bionic-pgdg Release' does not have a Release file.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I don't know too much about apt-get.

I then entered in the URL in question in my browser,  http://apt.postgresql.org and got re-directed to https://wiki.postgresql.org/wiki/Apt

I noticed these lines in the News section:

2023-11-05: Ubuntu bionic (18.04) and kinetic (22.10) removed from apt.postgresql.org.
2023-08-17: Ubuntu bionic (18.04) moving to apt-archive.postgresql.org: https://www.postgresql.org/message-id/ZN4OigxPJA236qlg%40msg.df7cb.de

Screenshot:

![image](https://github.com/ome/omero-documentation/assets/40019379/b718ef5f-1a8c-4349-b75c-747a90f3b07f)

Thoughts?

Thanks!

**Comment by jburel** [comment]
Thanks 
We are removing the page since we are no longer supporting the platform

**Comment by pwalczysko** [comment]
> Thanks We are removing the page since we are no longer supporting the platform

@scuniff - a futher info to what @jburel wrote - once the removal of the page is executed, you should be able to verify its absence using link https://docs.openmicroscopy.org/omero/latest/sysadmins/unix/server-ubuntu1804-ice36.html

Note the replacement ``5.6.0`` -> ``latest`` I made in your link - please use always the link to the latest docs, thank you again
