### ISSUE TITLE
Issue  installing "OMERO.server installation on CentOS 7"

### ISSUE THREAD

**Issue by scuniff** [openmicroscopy/ome-documentation#2380]
I was doing the install via this link, https://omero.readthedocs.io/en/stable/sysadmins/unix/server-centos7-ice36.html

All was going well until this section:

```
Running OMERO.server
The following steps are run as the omero-server system user. (su - omero-server)

OMERO should now be set up. To start the server run:

omero admin start
```

This is the logging from my install:

```
[omero-server@ip-172-30-4-46 ~]$  omero admin start
WARNING: Your server has not been configured for production use.
See https://docs.openmicroscopy.org/omero/latest/sysadmins/server-performance.html?highlight=poolsize
for more information.
No descriptor given. Using etc/grid/default.xml
Waiting on startup. Use CTRL-C to exit
.............................
Failed to startup some components after 300 seconds
Calling "stop" on remaining components
Waiting on shutdown. Use CTRL-C to exit
......[omero-server@ip-172-30-4-46 ~]$
```

Thoughts?

Thanks!

**Comment by joshmoore** [comment]
What does `omero admin diagnostics` show?

**Comment by scuniff** [comment]
My CentOS is on a EC2.....


[omero-server@ip-172-30-4-46 ~]$
[omero-server@ip-172-30-4-46 ~]$ uname -a
Linux ip-172-30-4-46.ec2.internal 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[omero-server@ip-172-30-4-46 ~]$
[omero-server@ip-172-30-4-46 ~]$
[omero-server@ip-172-30-4-46 ~]$
[omero-server@ip-172-30-4-46 ~]$
[omero-server@ip-172-30-4-46 ~]$ omero admin diagnostics

================================================================================
OMERO Diagnostics (admin)
================================================================================

Commands:   java -version                  11.0.21   (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 11.22     (/bin/psql)
Commands:   openssl version                1.0.2     (/bin/openssl)

Component:  OMERO.py                       5.17.0
Component:  OMERO.server                   5.6.9-ice36

Server:     icegridnode                    not started

Log dir:    /opt/omero/server/OMERO.server/var/log exists
Log files:  Blitz-0.log                    31.2 KB       errors=0    warnings=14
Log files:  DropBox.log                    n/a
Log files:  FileServer.log                 n/a
Log files:  Indexer-0.log                  21.6 KB       errors=0    warnings=21
Log files:  MonitorServer.log              n/a
Log files:  PixelData-0.log                10.5 KB
Log files:  Processor-0.log                50.4 KB       errors=9    warnings=36
Log files:  Tables-0.log                   52.7 KB       errors=9    warnings=36
Log files:  TestDropBox.log                n/a
Log files:  master.err                     16.4 KB       errors=0    warnings=4
Log files:  master.out                     1.5 KB
Log files:  Total size                     0.18 MB


Environment:OMERO_HOME=(unset)
Environment:OMERODIR=/opt/omero/server/OMERO.server
Environment:OMERO_NODE=(unset)
Environment:OMERO_MASTER=(unset)
Environment:OMERO_USERDIR=(unset)
Environment:OMERO_TMPDIR=(unset)
Environment:PATH=/opt/omero/server/venv3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/omero-server/.local/bin:/home/omero-server/bin
Environment:PYTHONPATH=(unset)
Environment:ICE_HOME=(unset)
Environment:LD_LIBRARY_PATH=(unset)
Environment:DYLD_LIBRARY_PATH=(unset)

Cannot list deployed applications.
OMERO data dir:'/OMERO'                       Exists? True      Is writable? True
OMERO temp dir:'/home/omero-server/omero/tmp' Exists? True      Is writable? True   (Size: 0)

JVM settings: Blitz-${index}                -Xmx512m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx341m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx512m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx341m -XX:MaxPermSize=256m -XX:+IgnoreUnrecognizedVMOptions

Jar:        lib/server/formats-api.jar     Bio-Formats API      7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/formats-bsd.jar     BSD Bio-Formats readers and writers  7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/formats-gpl.jar     Bio-Formats library  7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/ome-codecs.jar      OME Codecs   1.0.0   27 July 2023    c1c7b429a1b2b2ed3c619326bdc9cc4de71bb348
Jar:        lib/server/ome-common.jar      OME Common Java      6.0.19  27 July 2023    1d0b29ee0cd5bfed414c3499a0f0932f6ab7e2b7
Jar:        lib/server/ome-jai.jar         OME JAI      0.1.3   3 August 2018   489959cb7d24c279249bc08181aa9f734158ca4e
Jar:        lib/server/ome-mdbtools.jar    MDB Tools (Java port)        5.3.2   7 August 2018   68ffca2a95750cbb96f0d11785851aa4a554c0a4
Jar:        lib/server/ome-poi.jar         OME POI      5.3.7   5 July 2022     79a44040fa896a7c78b4e25da6ba7f4dda204c8e
Jar:        lib/server/ome-xml.jar         OME XML library      6.3.3   7 April 2023    64ede2afed98decf071c971c16e2b7c39e7e175b
Jar:        lib/server/omero-blitz.jar     jar  5.7.1
Jar:        lib/server/omero-common.jar    jar  5.6.3
Jar:        lib/server/omero-gateway.jar   jar  5.8.2
Jar:        lib/server/omero-model.jar     jar  5.6.12
Jar:        lib/server/omero-renderer.jar  jar  5.5.14
Jar:        lib/server/omero-romio.jar     jar  5.7.4
Jar:        lib/server/omero-server.jar    jar  5.6.9




I see some refernce to "errors" above in   

```
Log files:  Processor-0.log                50.4 KB       errors=9    warnings=36
Log files:  Tables-0.log                   52.7 KB       errors=9    warnings=36
```

Attached is install-4.log,  is a cut and paste of my install, hopefully I got it all pasted correctly.

Look for **possible issue**, I did have an issue with a SSL Cipher step....

```
possible issues

[omero-server@ip-172-30-4-46 ~]$ omero config set omero.glacier2.IceSSL.Ciphers=HIGH:!DH
-bash: !DH: event not found
[omero-server@ip-172-30-4-46 ~]$ omero config set omero.glacier2.IceSSL.Ciphers=HIGH:DH
 "=" in key name. Did you mean "...set omero.glacier2.IceSSL.Ciphers HIGH:DH"?


[omero-server@ip-172-30-4-46 ~]$  omero config set omero.glacier2.IceSSL.Ciphers HIGH:DH
[omero-server@ip-172-30-4-46 ~]$
```

Thanks!

[install-4.log](https://github.com/ome/omero-documentation/files/13478497/install-4.log)

**Comment by scuniff** [comment]
Attached are Processor-0.log and Tables-0.log, the log files that had errors from above......

[Processor-0.log](https://github.com/ome/omero-documentation/files/13484106/Processor-0.log)
[Tables-0.log](https://github.com/ome/omero-documentation/files/13484107/Tables-0.log)

**Comment by joshmoore** [comment]
Thanks for all the info, @scuniff. The fact that Processor and Tables *tried* to start implies to me that the main Blitz process began but then shutback down. Could you also share `master.out`, `master.err` and `Blitz-0.log`? Thanks.

**Comment by scuniff** [comment]
Here are the rest of the log files.....

I had to rename master.out and master.err because they were not allowed to be added as attachments.


[Blitz-0.log](https://github.com/ome/omero-documentation/files/13487088/Blitz-0.log)
[Indexer-0.log](https://github.com/ome/omero-documentation/files/13487090/Indexer-0.log)
[master.err.LOG](https://github.com/ome/omero-documentation/files/13487107/master.err.LOG)
[master.out.LOG](https://github.com/ome/omero-documentation/files/13487108/master.out.LOG)


Thank you.

**Comment by scuniff** [comment]
One more..... :)

[PixelData-0.log](https://github.com/ome/omero-documentation/files/13487157/PixelData-0.log)

**Comment by scuniff** [comment]
I'm seeing some Java memory errors in master.out.


I'll review and increase the RAM on my EC2.



From master.log:

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 39378944 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid13606.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 66895872 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid13622.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 69173248 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid1779.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 67084288 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid1812.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 63524864 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid1876.log

```


From /opt/omero/server/OMERO.server-5.6.9-ice36/hs_err_pid1876.log    (which is attached)

i see  **Increase physical memory or swap space**





```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 63524864 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:3229), pid=1876, tid=1879
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-11.0.21.0.9-1.el7_9) (11.0.21+9) (build 11.0.21+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-11.0.21.0.9-1.el7_9) (11.0.21+9-LTS, mixed mode, sharing, tiered, compressed oops, serial gc, linux-amd64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```
[hs_err_pid1876.log](https://github.com/ome/omero-documentation/files/13490524/hs_err_pid1876.log)

**Comment by scuniff** [comment]
Yikes!!

1G of RAM on my EC2,  my bad.

For some reason i thought the default was 8G.....

Will increase and let you know

**Comment by scuniff** [comment]
Ugh.

From AWS EC2 console, I had accidently picked t2.micro(1Gb RAM) where I usually pick t2.large(8Gb RAM).

I changed my EC2 to t2.large and things went well.
**omero admin start** finished in 10 seconds

```
[omero-server@ip-172-30-4-46 ~]$  omero admin start
WARNING: Your server has not been configured for production use.
See https://docs.openmicroscopy.org/omero/latest/sysadmins/server-performance.html?highlight=poolsize
for more information.
No descriptor given. Using etc/grid/default.xml
Waiting on startup. Use CTRL-C to exit
[omero-server@ip-172-30-4-46 ~]$
```

I see 3 java processes
```
[omero-server@ip-172-30-4-46 ~]$ ps -ef|grep java
omero-s+  1847  1815 99 00:42 ?        00:00:43 java -Xmx2498m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions -Djava.awt.headless=true -Dlogback.configurationFile=etc/logback.xml -Domero.logfile=var/log/${omero.name}.log -Domero.name=Blitz-0 ome.services.blitz.Entry --Ice.Config=/opt/omero/server/OMERO.server-5.6.9-ice36/var/master/servers/Blitz-0/config/config
omero-s+  1877  1815 76 00:42 ?        00:00:22 java -Xmx1665m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions -Djava.awt.headless=true -Dlogback.configurationFile=etc/logback-indexing.xml -Domero.logfile=var/log/${omero.name}.log -Domero.name=Indexer-0 ome.services.blitz.Entry ome.fulltext --Ice.Config=/opt/omero/server/OMERO.server-5.6.9-ice36/var/master/servers/Indexer-0/config/config
omero-s+  1899  1815 94 00:42 ?        00:00:28 java -Xmx2498m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions -Djava.awt.headless=true -Dlogback.configurationFile=etc/logback-indexing.xml -Domero.logfile=var/log/${omero.name}.log -Domero.name=PixelData-0 ome.services.blitz.Entry ome.pixeldata --Ice.Config=/opt/omero/server/OMERO.server-5.6.9-ice36/var/master/servers/PixelData-0/config/config
```

I think **omero admin diagnostics** looks good....

```
[omero-server@ip-172-30-4-46 ~]$ omero admin diagnostics

================================================================================
OMERO Diagnostics (admin)
================================================================================

Commands:   java -version                  11.0.21   (/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/bin/icegridadmin)
Commands:   psql --version                 11.22     (/bin/psql)
Commands:   openssl version                1.0.2     (/bin/openssl)

Component:  OMERO.py                       5.17.0
Component:  OMERO.server                   5.6.9-ice36

Server:     icegridnode                    running
Server:     Blitz-0                        active (pid = 1847, enabled)
Server:     DropBox                        inactive (disabled)
Server:     FileServer                     inactive (disabled)
Server:     Indexer-0                      active (pid = 1877, enabled)
Server:     MonitorServer                  inactive (disabled)
Server:     OMERO.Glacier2                 active (pid = 1880, enabled)
Server:     OMERO.IceStorm                 active (pid = 1887, enabled)
Server:     PixelData-0                    active (pid = 1899, enabled)
Server:     Processor-0                    active (pid = 1906, enabled)
Server:     Tables-0                       active (pid = 1916, enabled)
Server:     TestDropBox                    inactive (enabled)

Log dir:    /opt/omero/server/OMERO.server/var/log exists
Log files:  Blitz-0.log                    2.4 MB        errors=3    warnings=26
Log files:  DropBox.log                    n/a
Log files:  FileServer.log                 n/a
Log files:  Indexer-0.log                  36.2 KB       errors=0    warnings=25
Log files:  MonitorServer.log              n/a
Log files:  PixelData-0.log                19.8 KB       errors=0    warnings=4
Log files:  Processor-0.log                200.6 KB      errors=9    warnings=38
Log files:  Tables-0.log                   55.7 KB       errors=9    warnings=38
Log files:  TestDropBox.log                n/a
Log files:  master.err                     60.0 KB       errors=0    warnings=7
Log files:  master.out                     1.5 KB
Log files:  Total size                     2.77 MB


Environment:OMERO_HOME=(unset)
Environment:OMERODIR=/opt/omero/server/OMERO.server
Environment:OMERO_NODE=(unset)
Environment:OMERO_MASTER=(unset)
Environment:OMERO_USERDIR=(unset)
Environment:OMERO_TMPDIR=(unset)
Environment:PATH=/opt/omero/server/venv3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/omero-server/.local/bin:/home/omero-server/bin
Environment:PYTHONPATH=(unset)
Environment:ICE_HOME=(unset)
Environment:LD_LIBRARY_PATH=(unset)
Environment:DYLD_LIBRARY_PATH=(unset)

OMERO SSL port:4064
OMERO TCP port:4063
OMERO data dir:'/OMERO'                       Exists? True      Is writable? True
OMERO temp dir:'/home/omero-server/omero/tmp' Exists? True      Is writable? True   (Size: 0)

JVM settings: Blitz-${index}                -Xmx2498m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Indexer-${index}              -Xmx1665m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: PixelData-${index}            -Xmx2498m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions
JVM settings: Repository-${index}           -Xmx1665m -XX:MaxPermSize=1g -XX:+IgnoreUnrecognizedVMOptions

Jar:        lib/server/formats-api.jar     Bio-Formats API      7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/formats-bsd.jar     BSD Bio-Formats readers and writers  7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/formats-gpl.jar     Bio-Formats library  7.0.0   1 August 2023   3f8b3326cb578d59bd948fb84c838ff77e9f1b08
Jar:        lib/server/ome-codecs.jar      OME Codecs   1.0.0   27 July 2023    c1c7b429a1b2b2ed3c619326bdc9cc4de71bb348
Jar:        lib/server/ome-common.jar      OME Common Java      6.0.19  27 July 2023    1d0b29ee0cd5bfed414c3499a0f0932f6ab7e2b7
Jar:        lib/server/ome-jai.jar         OME JAI      0.1.3   3 August 2018   489959cb7d24c279249bc08181aa9f734158ca4e
Jar:        lib/server/ome-mdbtools.jar    MDB Tools (Java port)        5.3.2   7 August 2018   68ffca2a95750cbb96f0d11785851aa4a554c0a4
Jar:        lib/server/ome-poi.jar         OME POI      5.3.7   5 July 2022     79a44040fa896a7c78b4e25da6ba7f4dda204c8e
Jar:        lib/server/ome-xml.jar         OME XML library      6.3.3   7 April 2023    64ede2afed98decf071c971c16e2b7c39e7e175b
Jar:        lib/server/omero-blitz.jar     jar  5.7.1
Jar:        lib/server/omero-common.jar    jar  5.6.3
Jar:        lib/server/omero-gateway.jar   jar  5.8.2
Jar:        lib/server/omero-model.jar     jar  5.6.12
Jar:        lib/server/omero-renderer.jar  jar  5.5.14
Jar:        lib/server/omero-romio.jar     jar  5.7.4
Jar:        lib/server/omero-server.jar    jar  5.6.9
```


Thoughts??

Thanks!
